#!/bin/bash

CURRENT_GOVERNOR="/sys/devices/system/cpu/cpu*/cpufreq/scaling_governor"
CURRENT_ENERGY="/sys/devices/system/cpu/cpu*/cpufreq/energy_performance_preference"
CURRENT_BOOST="/sys/devices/system/cpu/intel_pstate/no_turbo"

set_governor() {
    for FILE in $CURRENT_GOVERNOR; do
        echo "$1" | sudo tee "$FILE" > /dev/null
    done
}

set_energy_mode() {
    for FILE in $CURRENT_ENERGY; do
        echo "$1" | sudo tee "$FILE" > /dev/null
    done
}

set_boost() {
    echo "$1" | sudo tee "$CURRENT_BOOST" > /dev/null
}

switch_governor() {
    if [ "$1" == "powersave" ]; then
        set_boost 0
        set_governor "powersave"
        set_energy_mode "power"
        hypridle &
    else
        set_boost 1
        set_governor "performance"
        set_energy_mode "performance"
    fi
}

POWER_STATUS=$(cat /sys/class/power_supply/AC0/online)

if [ "$POWER_STATUS" -eq 1 ]; then
    switch_governor performance
else
    switch_governor powersave
fi

udevadm monitor --udev --property | while IFS= read -r LINE; do
    if [[ "$LINE" == POWER_SUPPLY_ONLINE=* ]]; then
        POWER_STATUS="${LINE#*=}"
        if [ "$POWER_STATUS" -eq 1 ]; then
            switch_governor performance
        else
            switch_governor powersave
        fi
    fi
done

