#!/bin/bash

CURRENT_GOVERNOR="/sys/devices/system/cpu/cpu*/cpufreq/scaling_governor"
CURRENT_MIN_FREQ="/sys/devices/system/cpu/cpu*/cpufreq/scaling_min_freq"
CURRENT_ENERGY="/sys/devices/system/cpu/cpu*/cpufreq/energy_performance_preference"
CURRENT_BOOST="/sys/devices/system/cpu/intel_pstate/no_turbo"

set_governor() {
    for FILE in $CURRENT_GOVERNOR; do
        echo "$1" | sudo tee "$FILE" > /dev/null
    done
}

set_cpu_min_freq() {
    if [ "$1" == "min" ]; then
        for FILE in $CURRENT_MIN_FREQ; do
            echo "400000" | sudo tee "$FILE" > /dev/null
        done
    else
        for FILE in $CURRENT_MIN_FREQ; do
            echo "2400000" | sudo tee "$FILE" > /dev/null
        done
    fi
}

set_energy_mode() {
    for FILE in $CURRENT_ENERGY; do
        echo "$1" | sudo tee "$FILE" > /dev/null
    done
}

disable_boost() {
    echo "$1" | sudo tee "$CURRENT_BOOST" > /dev/null
}

switch_governor() {
    if [ "$1" == "powersave" ]; then
        disable_boost 1
        set_governor "powersave"
        set_energy_mode "power"
        set_cpu_min_freq "min"
        if [ $(pgrep hypridle) == "" ]; then
            hypridle &
        fi
    else
        disable_boost 0
        set_governor "performance"
        set_energy_mode "performance"
        set_cpu_min_freq "max"
    fi
}

POWER_STATUS=$(cat /sys/class/power_supply/AC0/online)

if [ "$POWER_STATUS" -eq 1 ]; then
    switch_governor performance
else
    switch_governor powersave
fi

udevadm monitor --udev --property | while IFS= read -r LINE; do
    if [[ "$LINE" == POWER_SUPPLY_ONLINE=* ]]; then
        POWER_STATUS="${LINE#*=}"
        if [ "$POWER_STATUS" -eq 1 ]; then
            switch_governor performance
        else
            switch_governor powersave
        fi
    fi
done

